#!/bin/bash
# GCP Helper Script - Common commands for DynaPrompt project
# Save this and run: bash gcp_helper.sh

echo "================================================================================"
echo "GCP DYNAPROMPT HELPER - Common Commands"
echo "================================================================================"
echo ""

# Get GCP IP
GCP_IP="35.245.145.0"  # Update this with your actual IP if different
USER="zk2295"

echo "📍 Your GCP VM: $USER@$GCP_IP"
echo ""

echo "================================================================================"
echo "1️⃣  NAVIGATE TO PROJECT"
echo "================================================================================"
echo "cd ~/myproject/6694-DynaPrompt"
echo ""

echo "================================================================================"
echo "2️⃣  UPDATE CODE FROM GITHUB"
echo "================================================================================"
echo "git pull origin zk2295"
echo ""

echo "================================================================================"
echo "3️⃣  RUN SCRIPTS"
echo "================================================================================"
echo "# Quick test (2 images, ~1 min each):"
echo "python scripts/quick_hybrid_test.py"
echo ""
echo "# Baseline vs Hybrid comparison (quantitative metrics):"
echo "python scripts/baseline_vs_hybrid.py"
echo ""

echo "================================================================================"
echo "4️⃣  DOWNLOAD RESULTS TO YOUR LOCAL MACHINE"
echo "================================================================================"
echo "Run these commands on your LOCAL Windows machine (not on GCP):"
echo ""
echo "# Download hybrid test results:"
echo "scp -r $USER@$GCP_IP:~/myproject/6694-DynaPrompt/outputs/hybrid_quick_test C:\\Users\\zisho\\Downloads\\"
echo ""
echo "# Download baseline vs hybrid comparison:"
echo "scp -r $USER@$GCP_IP:~/myproject/6694-DynaPrompt/outputs/baseline_vs_hybrid C:\\Users\\zisho\\Downloads\\"
echo ""
echo "# Download ALL outputs:"
echo "scp -r $USER@$GCP_IP:~/myproject/6694-DynaPrompt/outputs C:\\Users\\zisho\\Downloads\\"
echo ""

echo "================================================================================"
echo "5️⃣  VIEW METRICS (on GCP)"
echo "================================================================================"
echo "# View JSON metrics:"
echo "cat outputs/baseline_vs_hybrid/*_metrics.json | python -m json.tool"
echo ""
echo "# List all output files:"
echo "ls -lh outputs/baseline_vs_hybrid/"
echo "ls -lh outputs/hybrid_quick_test/"
echo ""

echo "================================================================================"
echo "6️⃣  CLEANUP (FREE UP SPACE)"
echo "================================================================================"
echo "# Remove old outputs:"
echo "rm -rf outputs/hybrid_quick_test/*"
echo "rm -rf outputs/baseline_vs_hybrid/*"
echo ""
echo "# Clear GPU cache (run after each test in Python):"
echo "import torch; torch.cuda.empty_cache()"
echo ""

echo "================================================================================"
echo "7️⃣  TROUBLESHOOTING"
echo "================================================================================"
echo "# Check GPU usage:"
echo "nvidia-smi"
echo ""
echo "# Check disk space:"
echo "df -h"
echo ""
echo "# Check if process is running:"
echo "ps aux | grep python"
echo ""
echo "# Kill stuck process (if needed):"
echo "pkill -f python"
echo ""

echo "================================================================================"
echo "8️⃣  QUICK WORKFLOW"
echo "================================================================================"
echo "# Standard workflow:"
echo "cd ~/myproject/6694-DynaPrompt"
echo "git pull origin zk2295"
echo "python scripts/baseline_vs_hybrid.py"
echo "# Then download on Windows: scp -r $USER@$GCP_IP:~/myproject/6694-DynaPrompt/outputs/baseline_vs_hybrid C:\\Users\\zisho\\Downloads\\"
echo ""

echo "================================================================================"
echo "✅ DONE - Copy the commands you need!"
echo "================================================================================"
